name: plant-music
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - jupyter
  - nbformat
  - ipykernel
  - pyyaml
  - matplotlib
  - pip
  - pip:
      - mido
      - pretty_midi
      - midi2audio
